# Generated by Django 3.0.5 on 2020-04-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mysearch', '0002_delete_clean_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='clean_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.TextField()),
                ('title', models.TextField()),
                ('authors', models.TextField()),
                ('affiliations', models.TextField()),
                ('abstract', models.TextField()),
                ('text', models.TextField()),
                ('bibliography', models.TextField()),
                ('raw_authors', models.TextField()),
                ('raw_bibliography', models.TextField()),
            ],
        ),
    ]
