# Generated by Django 3.0.5 on 2020-04-25 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysearch', '0003_clean_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clean_data',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='clean_data',
            name='affiliations',
        ),
        migrations.RemoveField(
            model_name='clean_data',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='clean_data',
            name='bibliography',
        ),
        migrations.RemoveField(
            model_name='clean_data',
            name='paper_id',
        ),
        migrations.RemoveField(
            model_name='clean_data',
            name='raw_authors',
        ),
        migrations.RemoveField(
            model_name='clean_data',
            name='raw_bibliography',
        ),
        migrations.RemoveField(
            model_name='clean_data',
            name='text',
        ),
        migrations.RemoveField(
            model_name='clean_data',
            name='title',
        ),
    ]
