# Generated by Django 3.0.5 on 2020-04-25 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysearch', '0004_auto_20200425_1945'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='clean_data',
            new_name='clean_data_test',
        ),
    ]
