# Generated by Django 3.0.5 on 2020-04-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysearch', '0005_auto_20200425_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='clean_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.TextField()),
                ('title', models.TextField()),
                ('authors', models.TextField()),
                ('affiliations', models.TextField()),
                ('abstract', models.TextField()),
                ('text', models.TextField()),
                ('bibliography', models.TextField()),
                ('raw_authors', models.TextField()),
                ('raw_bibliography', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='clean_data_test',
        ),
    ]
