# Generated by Django 3.0.5 on 2020-04-25 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysearch', '0006_auto_20200425_2019'),
    ]

    operations = [
        migrations.DeleteModel(
            name='clean_data',
        ),
    ]
